# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d8732d601f2fd0402be609c37687d01a76a97e4f189be254ff2ca3251db45ac25a8afd109e2515b28508811a76d26dd6aa21470d422a098bd3ed70f82d89125

test:
  secret_key_base: e9002166961e62afebed2d597e5eeed317ca0c294ddd4f9cc23a0e772fe8798206406d8c7f0e71a90d33adc6cc3b7b0cd6936ea8a41f24682b91593f166c4276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
