# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f0b06f644658397d89fdb1cbe0e55e06c5db53e3069f82543d7d91bf0697837f9333f69ed7cd526651db287b400ed06b6e21d493ea1df849fcb0a7e4c361e8b

test:
  secret_key_base: 6a20fcb2068633f0159745f2d44774e20a624c7de911c6a20f62928a8a72b6497d93743df09ba650bc610fab1a7930f12950517abf35832a1dec30ff3b465a99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
